### ISSUE TITLE
Consider changing the subtitle for this repository to be gender neutral

### ISSUE THREAD

**Issue by practicingdev** [MorganGeek/bookmarks#2]
This looks like a super cool collection of links!

It's worth noting though, that `craftsmen` is a gender specific term. Changing that to "software developers" or "software crafters" or really anything else would make your messaging more inclusive.

**Comment by SansGuidon** [comment]
@practicingdev Hi, thanks for your good remark, I'll add the gender neutral title to the subtitle but I keep the original "software craftsmanship" in topics for visibility (in search results etc) until crafter / craftership gains more visibility in github topics

Cheers
Morgan
