### ISSUE TITLE
The repository should be split

### ISSUE THREAD

**Issue by absynth76** [MorganGeek/bookmarks#7]
According to the amount of link referenced in that single page, this repo could/should be split per category :D 
who said bookmarks is easy ?

**Comment by SansGuidon** [comment]
It's true, but one thing that always repel me to do this is that I tend to like to have all content available at the same location to avoid having to edit too many files when adding a link, and avoid having to open many files to search through / reorganize the content. But of course given how GitHub truncates the content of big files, I'll be forced to do that, but I really delay that with all my strength ;p
